# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Yixue Wendy Feng
tagline:          'Home'
description:      "Neuro PhD @USC"
url:              http://wendyfyx.github.io/
baseurl:          /

# Collections
collections:
  projects:
    output : true
  research:
    output : true

# Default
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - jemoji